pipelines:

  GermlineEnrichment-2.5.3-IlluminaTruSightCancer:
    qc_checks: [pct_q30, fastqc, contamination, ntc_contamination, sex_match]
    min_q30_score: 0.75
    contamination_cutoff: 0.025
    ntc_contamination_cutoff: 10
    min_fastq_size: 1000000
    sample_expected_files: ['*.bam',
                '*.g.vcf',
                  '*_AlignmentSummaryMetrics.txt',
                  '*_Contamination.selfSM',
                  '*_DepthOfCoverage.gz',
                  '*_HsMetrics.txt',
                  '*_InsertMetrics.txt',
                  '*_MarkDuplicatesMetrics.txt',
                  '*_QC.txt']
    sample_not_expected_files: ['*_rmdup.bam',
                   '*_DepthOfCoverage']
    run_expected_files: ['*_filtered_annotated_roi.vcf',
                '*_filtered_annotated_roi_noMT.vcf',
                '*_pedigree.ped',
                '*_CollectVariantCallingMetrics.txt.variant_calling_detail_metrics',
                '*_CollectVariantCallingMetrics.txt.variant_calling_summary_metrics',
                '*_ExomeDepth_Metrics.txt',
                '*_relatedness.relatedness2',
                'combined_QC.txt',
                '*_cnvReport.csv']
    run_not_expected_files: ['*_variants_filtered.vcf',
                'BAMs.list']

  GermlineEnrichment-2.5.3-IlluminaTruSightOne:
    qc_checks: [pct_q30, fastqc, contamination, ntc_contamination, sex_match]
    min_q30_score: 0.8
    contamination_cutoff: 0.025
    ntc_contamination_cutoff: 10
    min_fastq_size: 1000000
    sample_expected_files: ['*.bam',
                '*.g.vcf',
                  '*_AlignmentSummaryMetrics.txt',
                  '*_Contamination.selfSM',
                  '*_DepthOfCoverage.gz',
                  '*_HsMetrics.txt',
                  '*_InsertMetrics.txt',
                  '*_MarkDuplicatesMetrics.txt',
                  '*_QC.txt']
    sample_not_expected_files: ['*_rmdup.bam',
                   '*_DepthOfCoverage']
    run_expected_files: ['*_filtered_annotated_roi.vcf',
                '*_filtered_annotated_roi_noMT.vcf',
                '*_pedigree.ped',
                '*_CollectVariantCallingMetrics.txt.variant_calling_detail_metrics',
                '*_CollectVariantCallingMetrics.txt.variant_calling_summary_metrics',
                '*_ExomeDepth_Metrics.txt',
                '*_relatedness.relatedness2',
                'combined_QC.txt']
    run_not_expected_files: ['*_variants_filtered.vcf',
                'BAMs.list']

  GermlineEnrichment-2.5.4-AgilentOGTFH:
    qc_checks: [pct_q30, fastqc, ntc_contamination]
    min_q30_score: 0.8
    contamination_cutoff: 0.025
    ntc_contamination_cutoff: 10
    min_fastq_size: 1000000
    sample_expected_files: ['*.bam',
                '*.g.vcf',
                  '*_AlignmentSummaryMetrics.txt',
                  '*_Contamination.selfSM',
                  '*_DepthOfCoverage.gz',
                  '*_HsMetrics.txt',
                  '*_InsertMetrics.txt',
                  '*_MarkDuplicatesMetrics.txt',
                  '*_QC.txt',
                  '*_FH_VariantReport_filtered.csv']
    sample_not_expected_files: ['*_rmdup.bam',
                   '*_DepthOfCoverage']
    run_expected_files: ['*_filtered_annotated_roi.vcf',
                '*_filtered_annotated_roi_noMT.vcf',
                '*_pedigree.ped',
                '*_CollectVariantCallingMetrics.txt.variant_calling_detail_metrics',
                '*_CollectVariantCallingMetrics.txt.variant_calling_summary_metrics',
                '*_relatedness.relatedness2',
                'sv_analysis/*_cnvReport.csv',
                'combined_QC.txt',
              ]
    run_not_expected_files: ['*_variants_filtered.vcf',
                'BAMs.list']

  SomaticEnrichment-1.0.0-RochePanCancer:
    qc_checks: [pct_q30, fastqc, ntc_contamination, sex_match]
    min_q30_score: 0.8
    contamination_cutoff: 0.025
    ntc_contamination_cutoff: 10
    min_fastq_size: 1000000
    sample_expected_files: ['*_VariantReport.txt',
                  '*.bam',
                  '*_AlignmentSummaryMetrics.txt',
                  '*_DepthOfCoverage.sample_summary',
                  '*_QC.txt',
                  '*_filteredStrLeftAligned_annotated.vcf',
                  'hotspot_variants',
                  'hotspot_coverage_135x'
                  ]
    sample_not_expected_files: []
    run_sample_expected_files: ['CNVKit/*_common.vcf']
    run_expected_files: ['combined_QC.txt', 'samplesCNVKit.txt']
    run_not_expected_files: ['*.bed']

  SomaticAmplicon-1.7.6-NGHS-102X:
    min_q30_score: 0.8
    contamination_cutoff: 0.025
    ntc_contamination_cutoff: 10
    qc_checks: [pct_q30, fastqc, ntc_contamination]
    min_fastq_size: 10000000
    sample_expected_files: ['*_VariantReport.txt',
                  '*.bam',
                  '*_DepthOfCoverage.sample_summary',
                  '*_qc.txt',
                  '*_filtered_meta_annotated.vcf',
                  'hotspot_variants',
                  ]
    sample_not_expected_files: ['*_fastqc.zip', 'VariantCallingLogs']
    run_expected_files: []
    run_not_expected_files: []

  SomaticAmplicon-1.7.6-NGHS-101X:
    min_q30_score: 0.8
    contamination_cutoff: 0.025
    ntc_contamination_cutoff: 10
    qc_checks: [pct_q30, fastqc, ntc_contamination]
    min_fastq_size: 10000000
    sample_expected_files: ['*_VariantReport.txt',
                  '*.bam',
                  '*_DepthOfCoverage.sample_summary',
                  '*_qc.txt',
                  '*_filtered_meta_annotated.vcf',
                  'hotspot_variants',
                  'hotspot_coverage'
                  ]
    sample_not_expected_files: ['*_fastqc.zip', 'VariantCallingLogs']
    run_expected_files: []
    run_not_expected_files: []

  SomaticAmplicon-1.7.7-NGHS-101X:
    min_q30_score: 0.8
    contamination_cutoff: 0.025
    ntc_contamination_cutoff: 10
    qc_checks: [pct_q30, fastqc, ntc_contamination]
    min_fastq_size: 10000000
    sample_expected_files: ['*_VariantReport.txt',
                  '*.bam',
                  '*_DepthOfCoverage.sample_summary',
                  '*_qc.txt',
                  '*_filtered_meta_annotated.vcf',
                  'hotspot_variants',
                  'hotspot_coverage'
                  ]
    sample_not_expected_files: ['*_fastqc.zip', 'VariantCallingLogs']
    run_expected_files: []
    run_not_expected_files: []

  SomaticAmplicon-1.7.7-NGHS-102X:
    min_q30_score: 0.8
    contamination_cutoff: 0.025
    ntc_contamination_cutoff: 10
    qc_checks: [pct_q30, fastqc, ntc_contamination]
    min_fastq_size: 10000000
    sample_expected_files: ['*_VariantReport.txt',
                  '*.bam',
                  '*_DepthOfCoverage.sample_summary',
                  '*_qc.txt',
                  '*_filtered_meta_annotated.vcf',
                  'hotspot_variants',
                  'hotspot_coverage'
                  ]
    sample_not_expected_files: ['*_fastqc.zip', 'VariantCallingLogs']
    run_expected_files: []
    run_not_expected_files: []
   





